### ISSUE TITLE
twilio monthly limit reached

### ISSUE THREAD

**Issue by imranariffin** [hooligram/hooligram-server#23]
It seems like our Twilio monthly limit for the project `hooligram` has been reached.

I kept getting the following error on my local server build:
```
wscat > {"type":"VERIFICATION_REQUEST_CODE_REQUEST","payload":{"country_code":"1","phone_number":"6478637073"}}
server: 2019/02/11 21:19:04 [V1] Twilio verification start API call failed.
wscat < {"payload":{},"type":"VERIFICATION_REQUEST_CODE_FAILURE"}
```
Until I switched the TWILIO_API_KEY to that of a different project (imran-test), after which I started getting back success and the SMS code.

This has been bugging me for quite a bit while working on and testing the front end. I think we need to create projects hooligram-2, hooligram-3 & hooligram-4 and keep switching every week in round robin or so lol 

What do you think? @cglotr

**Comment by cglotr** [comment]
> It seems like our Twilio monthly limit for the project `hooligram` has been reached.
> 
> I kept getting the following error on my local server build:
> 
> ```
> wscat > {"type":"VERIFICATION_REQUEST_CODE_REQUEST","payload":{"country_code":"1","phone_number":"6478637073"}}
> server: 2019/02/11 21:19:04 [V1] Twilio verification start API call failed.
> wscat < {"payload":{},"type":"VERIFICATION_REQUEST_CODE_FAILURE"}
> ```
> Until I switched the TWILIO_API_KEY to that of a different project (imran-test), after which I started getting back success and the SMS code.
> 
> This has been bugging me for quite a bit while working on and testing the front end. I think we need to create projects hooligram-2, hooligram-3 & hooligram-4 and keep switching every week in round robin or so lol
> 
> What do you think? @cglotr

hahaha let's do that for now
