### ISSUE TITLE
return token on sign in success

### ISSUE THREAD

**Issue by imranariffin** [hooligram/hooligram-server#25]
I just realized that unless server supplies the token, front end will have to hack its way to handle authorization. Authorization token has to be provided by the server not created by the client itself.

For now, a payload like the following is sufficient
```
{
  "code": "<number>",
  "country_code": "<number>",
  "phone_number": "<number>"
}
```

@cglotr lmk if this makes sense

**Comment by cglotr** [comment]
> I just realized that unless server supplies the token, front end will have to hack its way to handle authorization. Authorization token has to be provided by the server not created by the client itself.
> 
> For now, a payload like the following is sufficient
> 
> ```
> {
>   "code": "<number>",
>   "country_code": "<number>",
>   "phone_number": "<number>"
> }
> ```
> @cglotr lmk if this makes sense

yeah, makes sense to me. @imranariffin

**Comment by imranariffin** [comment]
Do you wanna work on it? 
@cglotr

**Comment by imranariffin** [comment]
Actually lemme do it, just realized it should be a very simple change.

@cglotr
