### ISSUE TITLE
init app action

### ISSUE THREAD

**Issue by imranariffin** [hooligram/hooligram-server#33]
Support a new action the client can use on app startup so backend will provide required values the client need to start app.

The values may include min app version, latest migration version, future business rules etc

Ideally the values should be configurable on the backend without need for deployment.

Suggestion:
```
// Request
{
  "type": "APP_INIT_REQUEST",
  payload: {}
}

// Response
{
  "type": "APP_INIT_SUCCESS",
  payload: {
    // values
  }
}
```

Related to https://github.com/hooligram/hooligram-client/issues/57

**Comment by cglotr** [comment]
Looks like a good idea. This action should be done before sign in actions right? Also, we are doing this after SQLite stuff is done right? @imranariffin

**Comment by imranariffin** [comment]
I think we should it first thing on the app even before sql ini. Sql init
will need to use some values from its response for e.g. `migrationVersion`

**Comment by imranariffin** [comment]
Oh in terms of dev, we can also do sql first just using a constant for
`migrationVersion`

**Comment by cglotr** [comment]
@imranariffin closing since I think this should be a part of *Hikaru*
