### ISSUE TITLE
30: support create group

### ISSUE THREAD

**Issue by cglotr** [hooligram/hooligram-server#35]
- The client is able to create a message group.
- Send group info to other members.

**Comment by imranariffin** [comment]
#### Actions

*User sends request to server to create a new group*
```
{
  "type": "GROUP_CREATE_REQUEST",
  "payload": {
    "name": <string>,
    "member_ids": <[<string>]>
  }
}
```
*Server responds to user group id and other group info*
```
{
  "type": "GROUP_CREATE_SUCCESS",
  "payload": {
    "id": <integer>,
    "name": <string>,
    "member_ids": <[<string>]>,
    "date_created": <string>
  }
}
```
*Server responds to user error*
```
{
  "type": "GROUP_CREATE_FAILURE",
  "payload": {
    "errors": <[<string>]>
  }
}
```

**Comment by imranariffin** [comment]
> * Send group info to other members.

@cglotr Does it even make sense to be in this issue? I believe it should be in the sibling issue #36 since there is no other member to begin with when the user first created a group.

**Comment by cglotr** [comment]
> > * Send group info to other members.
> 
> @cglotr Does it even make sense to be in this issue? I believe it should be in the sibling issue #36 since there is no other member to begin with when the user first created a group.

I think `GROUP_CREATE_REQUEST`'s payload should include the initial members of that group. For me, #36, is to support adding additional group member afterward.

`GROUP_CREATE_REQUEST` should also require to have > 1 initial group member ids.

**Comment by imranariffin** [comment]
> > > * Send group info to other members.
> > 
> > 
> > @cglotr Does it even make sense to be in this issue? I believe it should be in the sibling issue #36 since there is no other member to begin with when the user first created a group.
> 
> I think `GROUP_CREATE_REQUEST`'s payload should include the initial members of that group. For me, #36, is to support adding additional group member afterward.
> 
> `GROUP_CREATE_REQUEST` should also require to have > 1 initial group member ids.

Aaaah got it. So a group creator can always pre-add members into the group like this:
![whatsapp-add-group-member-when-creating-group](https://user-images.githubusercontent.com/5580715/54498096-ec884480-48d8-11e9-95ad-c03701e31503.png)

**Comment by cglotr** [comment]
#40
