### ISSUE TITLE
client unable to connect to server running locally

### ISSUE THREAD

**Issue by imranariffin** [hooligram/hooligram-server#5]
The mobile app can connect to server on ws://13.229.65.93:8080/echo. However when connecting to localhost (server is running locally), client gets 403 error.

**Comment by cglotr** [comment]
I am able to connect to `/echo` locally. Try following these steps and report back to me:
- `cd ~/go/src/github.com/hooligram/hooligram-server`
- `go build`
- `export PORT=8080`
- `export TWILIO_API_KEY=test`
- `./hooligram-server`
- `npm i -g wscat`
- `wscat -c ws://127.0.0.1:8080/echo`

@imranariffin

**Comment by imranariffin** [comment]
Method above works. I'll try connecting again from the app. Probably because android simulator is using 10.0.2.2 to map to localhost.
I will try follow something like this: https://futurestud.io/tutorials/how-to-run-an-android-app-against-a-localhost-api or somoething with the adb.

@cglotr
